// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using ReverseEngineered.Models;

namespace ReverseEngineered.Context;

public partial class CarsContext : DbContext
{
    public CarsContext(DbContextOptions<CarsContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Car> Cars { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Car>(entity =>
        {
            entity.HasKey(e => e.Num);

            entity.ToTable("Car");

            entity.Property(e => e.Color)
                .IsRequired()
                .HasMaxLength(16);
            entity.Property(e => e.Manufacture)
                .IsRequired()
                .HasMaxLength(32);
            entity.Property(e => e.Model)
                .IsRequired()
                .HasMaxLength(32);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}