// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using MVVMDay23.Model;
using Microsoft.EntityFrameworkCore;
using CarsData;

namespace MVVMDay23.DataAccess;

public partial class CarDataBaseContext : DbContext
{
    public CarDataBaseContext()
    {
    }

    public CarDataBaseContext(DbContextOptions<CarDataBaseContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Car> Cars { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer("Data Source=.;Initial Catalog=CarsContext;Integrated Security=True; Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Car>(entity =>
        {
            entity.HasKey(e => e.Num);

            entity.ToTable("Car");

            entity.Property(e => e.Color)
                .IsRequired()
                .HasMaxLength(16);
            entity.Property(e => e.Manufacture)
                .IsRequired()
                .HasMaxLength(32);
            entity.Property(e => e.Model)
                .IsRequired()
                .HasMaxLength(32);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}