// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MVVMDay23.Model;

public partial class Car
{
    public int Num { get; set; }

    public string Color { get; set; }

    public string Manufacture { get; set; }

    public string Model { get; set; }
}